Update error messages for exception tests
For test functions (in `Util/Util.fs`) like `throwsError` or `throwsAnyError`:
Previously error when an exception was expected, but not thrown, looked like:
> Error: Expected: true - Actual: false

Updated error messages:
> Error: Expected: Error "my error message" - Actual: Ok

or
> Error: Expected: Error "my error message" - Actual: Error "some other message"

* Add `throwsErrorContaining` test: Exception must contain passed error message (vs `throwsError`, which requires exact match of error message)
* Add `doesntThrow` test. For fast replacement (or same test layout) of `throwsXXX`
* Add unit tests for test methods